### ISSUE TITLE
Cannot find the keyfile on windows

### ISSUE THREAD

**Issue by makanig** [docusign/sample-app-mysure-python#4]
The os module does not work well when adding directory paths and the key file is not found on Windows.
I made a fix to ds_config.py to use the pathlib module to make it OS independent

**Comment by ivdinkovds** [comment]
@makanig, Please if you can share the your findings with example so we can reproduce the issue. Perhaps you can submit your improvement as pull request

**Comment by makanig** [comment]
@ivdinkovds here is the error when I run in windows: I have forked and made the change and did the pull request in my master. The file is ds_config.py. You can pick it up from there

1526, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.

**Comment by ivdinkovds** [comment]
@makanig usually this error is caused by key path. Try placing in the root ./private.key

**Comment by ivdinkovds** [comment]
I am going to close the issue as there was no response for a while, if you have other questions please file a new issue
