### ISSUE TITLE
Certificate on demo site has been revoked

### ISSUE THREAD

**Issue by timharsch** [docusign/sample-app-mysure-python#8]
![image](https://user-images.githubusercontent.com/61298249/116797541-a03df580-aa9b-11eb-8a94-d3de472fbb12.png)

**Comment by InbarGazit** [comment]
https://mysure.sampleapps.docusign.com/ is the correct URL, we'll fix the README.

**Comment by InbarGazit** [comment]
Thank you @timharsch  for reporting this! It has been fixed.
